// -----------------------------------------------------------------------------
// @generated by xtask/codegen (signed)
// DO NOT EDIT MANUALLY.
// Changes will be overwritten.
// -----------------------------------------------------------------------------

use super::*;

mod unit_tests {
    use super::*;
    use core::isize;

    fn span(lo: isize, hi: isize) -> IsizeCO {
        IsizeCO::try_new(lo, hi).unwrap()
    }

    #[test]
    fn scale_positive_basic() {
        let a = span(2, 5);
        let scaled = a.scale(3).unwrap();
        assert_eq!(scaled, span(6, 15));
    }

    #[test]
    fn scale_negative_basic() {
        let a = span(2, 5);
        let scaled = a.scale(-2).unwrap();
        assert_eq!(scaled, span(-10, -4));
    }

    #[test]
    fn scale_zero_returns_none() {
        let a = span(2, 5);
        assert_eq!(a.scale(0), None);
    }

    #[test]
    fn shift_positive_basic() {
        let a = span(1, 4);
        let shifted = a.shift(5).unwrap();
        assert_eq!(shifted, span(6, 9));
    }

    #[test]
    fn shift_negative_basic() {
        let a = span(1, 4);
        let shifted = a.shift(-2).unwrap();
        assert_eq!(shifted, span(-1, 2));
    }

    #[test]
    fn scale_positive_overflow_returns_none() {
        let a = span(isize::MAX / 2 + 1, isize::MAX);
        assert!(a.scale(2).is_none());
    }

    #[test]
    fn scale_negative_overflow_returns_none() {
        let a = span(isize::MIN + 1, -1);
        assert!(a.scale(-2).is_none());
    }

    #[test]
    fn shift_positive_overflow_returns_none() {
        let a = span(isize::MAX - 5, isize::MAX);
        assert!(a.shift(10).is_none());
    }

    #[test]
    fn shift_negative_overflow_returns_none() {
        let a = span(isize::MIN, isize::MIN + 5);
        assert!(a.shift(-1).is_none());
    }
}

mod prop_tests {
    use super::*;
    use core::isize;
    use proptest::prelude::*;
    use std::vec;

    fn edge_scalar() -> impl Strategy<Value = isize> {
        prop::sample::select(vec![isize::MIN, isize::MIN + 1, -1, 0, 1, isize::MAX - 1, isize::MAX])
    }

    fn nonzero_scalar() -> impl Strategy<Value = isize> {
        mixed_scalar().prop_filter("non-zero scalar", |&x| x != 0)
    }

    fn mixed_scalar() -> impl Strategy<Value = isize> {
        prop_oneof! {
            3 => edge_scalar(),
            7 => any::<isize>(),
        }
    }

    fn span_strategy() -> impl Strategy<Value = IsizeCO> {
        (mixed_scalar(), mixed_scalar()).prop_filter_map("non-empty interval", |(a, b)| {
            IsizeCO::try_new(a.min(b), a.max(b))
        })
    }

    #[inline]
    fn sample_points(x: IsizeCO) -> [isize; 4] {
        let start = x.start();
        let end_incl = x.end_incl();

        let near_start = if start < end_incl { start + 1 } else { start };
        let near_end = if start < end_incl {
            end_incl - 1
        } else {
            end_incl
        };

        [start, near_start, near_end, end_incl]
    }

    proptest! {
        #![proptest_config(ProptestConfig { cases: 64, .. ProptestConfig::default() })]

        #[test]
        fn shift_preserves_interval_invariant(x in span_strategy(), offset in mixed_scalar()) {
            if let Some(shifted) = x.shift(offset) {
                prop_assert!(shifted.start() < shifted.end_excl());
            }
        }

        #[test]
        fn scale_preserves_interval_invariant(x in span_strategy(), factor in nonzero_scalar()) {
            if let Some(scaled) = x.scale(factor) {
                prop_assert!(scaled.start() < scaled.end_excl());
            }
        }

        #[test]
        fn positive_scale_matches_endpoint_transform(
            x in span_strategy(),
            factor in 1isize..=isize::MAX
        ) {
            if let Some(scaled) = x.scale(factor) {
                prop_assert_eq!(scaled.start(), x.start() * factor);
                prop_assert_eq!(scaled.end_excl(), x.end_excl() * factor);
            }
        }

        #[test]
        fn negative_scale_matches_endpoint_transform(
            x in span_strategy(),
            factor in isize::MIN..=-1
        ) {
            if let Some(scaled) = x.scale(factor) {
                prop_assert_eq!(scaled.start(), x.end_excl() * factor);
                prop_assert_eq!(scaled.end_excl(), x.start() * factor);
            }
        }

        #[test]
        fn shift_preserves_sampled_membership(x in span_strategy(), offset in mixed_scalar()) {
            if let Some(shifted) = x.shift(offset) {
                for v in sample_points(x) {
                    if x.contains(v) {
                        let mapped = match v.checked_add(offset) {
                            Some(m) => m,
                            None => continue,
                        };
                        prop_assert!(shifted.contains(mapped));
                    }
                }
            }
        }
    }
}
