use std::{
    env, fs,
    path::{Path, PathBuf},
};

/// (primitive_type, struct_name)
const TYPES: &[(&str, &str)] = &[
    ("u8", "U8CO"),
    ("u16", "U16CO"),
    ("u32", "U32CO"),
    ("u64", "U64CO"),
    ("u128", "U128CO"),
    ("usize", "UsizeCO"),
    ("i8", "I8CO"),
    ("i16", "I16CO"),
    ("i32", "I32CO"),
    ("i64", "I64CO"),
    ("i128", "I128CO"),
    ("isize", "IsizeCO"),
];

fn main() {
    let root = workspace_root();
    let src = root.join("src");

    codegen_types(&src);
    write_lib(&src);
}

/// workspace 根目录
fn workspace_root() -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .parent() // xtask
        .unwrap()
        .parent() // workspace root
        .unwrap()
        .to_path_buf()
}

/// 生成所有整型 interval
fn codegen_types(src: &std::path::Path) {
    let template = fs::read_to_string(src.join("u8.rs")).unwrap();

    for (ty, name) in TYPES {
        if *ty == "u8" {
            continue;
        }

        generate_type(src, &template, ty, name);
        generate_tests(src, ty, name);
    }
}

const GENERATED_WARNING: &str = "\
// -----------------------------------------------------------------------------\n\
// @generated by xtask/codegen\n\
// DO NOT EDIT MANUALLY.\n\
// Changes will be overwritten.\n\
// -----------------------------------------------------------------------------\n\n";

/// 生成 interval struct
fn generate_type(src: &Path, template: &str, ty: &str, name: &str) {
    let body = template.replace("U8CO", name).replace("u8", ty);
    let code = format!("{GENERATED_WARNING}{body}");

    fs::write(src.join(format!("{ty}.rs")), code).unwrap();
}

/// 复制 tests
fn generate_tests(src: &Path, ty: &str, name: &str) {
    let src_tests = src.join("u8");
    let dst_tests = src.join(ty);

    fs::create_dir_all(&dst_tests).unwrap();

    for entry in fs::read_dir(src_tests).unwrap() {
        let path = entry.unwrap().path();
        let text = fs::read_to_string(&path).unwrap();

        let body = text.replace("U8CO", name).replace("u8", ty);
        let code = format!("{GENERATED_WARNING}{body}");

        let dst = dst_tests.join(path.file_name().unwrap());
        fs::write(dst, code).unwrap();
    }
}

/// 生成 lib.rs
fn write_lib(src: &Path) {
    let mut s = String::new();

    s.push_str("#![no_std]\n");
    s.push_str("#[cfg(test)]\n");
    s.push_str("extern crate std;\n\n");

    s.push_str("mod res;\n");

    for (ty, _) in TYPES {
        s.push_str(&format!("mod {ty};\n"));
    }

    s.push('\n');

    s.push_str("pub use res::{OneTwo, ZeroOneTwo};\n");

    for (ty, name) in TYPES {
        s.push_str(&format!("pub use {ty}::{name};\n"));
    }

    fs::write(src.join("lib.rs"), s).unwrap();
}
