// -----------------------------------------------------------------------------
// @generated by xtask/codegen (unsigned)
// DO NOT EDIT MANUALLY.
// Changes will be overwritten.
// -----------------------------------------------------------------------------

use super::*;

#[cfg(test)]
mod unit_tests {
    use core::u64;

    use super::*;

    #[test]
    fn test_minkowski_add_basic() {
        let a = U64CO::try_new(1, 5).unwrap();
        let b = U64CO::try_new(2, 4).unwrap();
        let res = a.minkowski_add(b).unwrap();
        // start = 1 + 2 = 3
        assert_eq!(res.start(), 3);
        // end_excl = (a.end_incl + b.end_incl + 1) = (4 + 3 + 1) = 8
        assert_eq!(res.end_excl(), 8);
    }

    #[test]
    fn test_minkowski_sub_basic() {
        let a = U64CO::try_new(5, 10).unwrap();
        let b = U64CO::try_new(2, 4).unwrap();
        let res = a.minkowski_sub(b).unwrap();
        assert_eq!(res.start(), 2); // 5 - 3
        assert_eq!(res.end_excl(), 8); // 9 - 2 + 1
    }

    #[test]
    fn test_minkowski_mul_basic() {
        let a = U64CO::try_new(1, 4).unwrap(); // [1,4)
        let b = U64CO::try_new(2, 3).unwrap(); // [2,3)
        let res = a.minkowski_mul(b).unwrap();
        assert_eq!(res.start(), 2); // 1*2
        assert_eq!(res.end_excl(), 7); // (3*2)+1
    }

    #[test]
    fn test_minkowski_div_basic() {
        let a = U64CO::try_new(4, 10).unwrap();
        let b = U64CO::try_new(2, 5).unwrap();
        let res = a.minkowski_div(b).unwrap();
        assert_eq!(res.start(), 1); // 4/4
        assert_eq!(res.end_excl(), 5); // 9/2 + 1
    }

    #[test]
    fn test_minkowski_div_by_zero() {
        let a = U64CO::try_new(1, 5).unwrap();
        let b = U64CO::try_new(0, 3).unwrap();
        assert!(a.minkowski_div(b).is_none());
    }

    #[test]
    fn test_minkowski_overflow() {
        let a = U64CO::try_new(250, u64::MAX).unwrap();
        let b = U64CO::try_new(10, 20).unwrap();
        assert!(a.minkowski_add(b).is_none());
        assert!(a.minkowski_mul(b).is_none());
    }
}

#[cfg(test)]
mod prop_tests {
    use super::*;
    use proptest::prelude::*;

    fn interval_strategy() -> impl Strategy<Value = U64CO> {
        prop_oneof![
            Just(U64CO::try_new(u64::MIN, u64::MIN + 1).unwrap()), // [0, 1)
            Just(U64CO::try_new(u64::MIN, u64::MAX).unwrap()),     // [0, 255)
            Just(U64CO::try_new(u64::MAX - 1, u64::MAX).unwrap()), // [254, 255)
            (u64::MIN..=u64::MAX, u64::MIN..=u64::MAX)
                .prop_filter_map("valid interval", |(s, e)| U64CO::try_new(s, e))
        ]
    }

    proptest! {
        #[test]
        fn prop_add_containment(a in interval_strategy(), b in interval_strategy()) {
            if let Some(c) = a.minkowski_add(b) {
                let xs = [a.start(), a.end_excl()-1];
                let ys = [b.start(), b.end_excl()-1];
                for &x in &xs {
                    for &y in &ys {
                        let sum = x.wrapping_add(y);
                        prop_assert!(c.start() <= sum && sum < c.end_excl());
                    }
                }
            }
        }

        #[test]
        fn prop_sub_containment(a in interval_strategy(), b in interval_strategy()) {
            if let Some(c) = a.minkowski_sub(b) {
                let xs = [a.start(), a.end_excl()-1];
                let ys = [b.start(), b.end_excl()-1];
                for &x in &xs {
                    for &y in &ys {
                        let diff = x.wrapping_sub(y);
                        prop_assert!(c.start() <= diff && diff < c.end_excl());
                    }
                }
            }
        }

        #[test]
        fn prop_mul_containment(a in interval_strategy(), b in interval_strategy()) {
            if let Some(c) = a.minkowski_mul(b) {
                let xs = [a.start(), a.end_excl()-1];
                let ys = [b.start(), b.end_excl()-1];
                for &x in &xs {
                    for &y in &ys {
                        let prod = x.wrapping_mul(y);
                        prop_assert!(c.start() <= prod && prod < c.end_excl());
                    }
                }
            }
        }

        #[test]
        fn prop_div_containment(a in interval_strategy(), b in interval_strategy().prop_filter("non-zero start", |b| b.start() != 0)) {
            if let Some(c) = a.minkowski_div(b) {
                let xs = [a.start(), a.end_excl()-1];
                let ys = [b.start(), b.end_excl()-1];
                for &x in &xs {
                    for &y in &ys {
                        let div = x / y;
                        prop_assert!(c.start() <= div && div < c.end_excl());
                    }
                }
            }
        }

        #[test]
        fn prop_add_commutative(a in interval_strategy(), b in interval_strategy()) {
            let res1 = a.minkowski_add(b);
            let res2 = b.minkowski_add(a);
            prop_assert_eq!(res1, res2);
        }

        #[test]
        fn prop_mul_commutative(a in interval_strategy(), b in interval_strategy()) {
            let res1 = a.minkowski_mul(b);
            let res2 = b.minkowski_mul(a);
            prop_assert_eq!(res1, res2);
        }
    }
}
