// -----------------------------------------------------------------------------
// @generated by xtask/codegen (signed)
// DO NOT EDIT MANUALLY.
// Changes will be overwritten.
// -----------------------------------------------------------------------------

use crate::res::{OneTwo, ZeroOneTwo};

#[cfg(test)]
mod between_tests;
#[cfg(test)]
mod checked_minkowski_tests;
#[cfg(test)]
mod convex_hull_tests;
#[cfg(test)]
mod difference_tests;
#[cfg(test)]
mod intersection_tests;
#[cfg(test)]
mod symmetric_difference_tests;
#[cfg(test)]
mod union_tests;

#[derive(Copy, Clone, Debug, Eq, PartialEq, Hash)]
pub struct I32CO {
    start: i32,
    end_excl: i32,
}

// ------------------------------------------------------------
// low-level api: construction / accessors / predicates
// ------------------------------------------------------------
mod construction_accessors_predicates {

    use super::*;

    impl I32CO {
        #[inline]
        pub const fn try_new(start: i32, end_excl: i32) -> Option<Self> {
            if start < end_excl {
                Some(Self { start, end_excl })
            } else {
                None
            }
        }

        #[inline]
        pub(super) const fn new_unchecked(start: i32, end_excl: i32) -> Self {
            debug_assert!(start < end_excl);
            Self { start, end_excl }
        }

        #[inline]
        pub const fn start(self) -> i32 {
            self.start
        }

        #[inline]
        pub const fn end_excl(self) -> i32 {
            self.end_excl
        }

        #[inline]
        pub const fn end_incl(self) -> i32 {
            // i32_low_bound =< start < end_excl
            self.end_excl - 1
        }

        #[inline]
        pub const fn len(self) -> u32 {
            (self.end_excl - self.start) as u32
        }

        #[inline]
        pub const fn contains(self, x: i32) -> bool {
            self.start <= x && x < self.end_excl
        }

        #[inline]
        pub const fn iter(self) -> core::ops::Range<i32> {
            self.start..self.end_excl
        }

        #[inline]
        pub const fn to_range(self) -> core::ops::Range<i32> {
            self.start..self.end_excl
        }

        #[inline]
        pub const fn intersects(self, other: Self) -> bool {
            !(self.end_excl <= other.start || other.end_excl <= self.start)
        }

        #[inline]
        pub const fn is_adjacent(self, other: Self) -> bool {
            self.end_excl == other.start || other.end_excl == self.start
        }

        #[inline]
        pub const fn is_contiguous_with(self, other: Self) -> bool {
            self.intersects(other) || self.is_adjacent(other)
        }
    }
}
// ------------------------------------------------------------
// interval algebra api: intersection / convex_hull / between / union / difference / symmetric_difference
// ------------------------------------------------------------

mod interval_algebra {

    use super::*;

    impl I32CO {
        /// Returns the intersection of two intervals.
        ///
        /// If the intervals do not overlap, returns `None`.
        #[inline]
        pub const fn intersection(self, other: Self) -> Option<Self> {
            let start = if self.start >= other.start {
                self.start
            } else {
                other.start
            };

            let end_excl = if self.end_excl <= other.end_excl {
                self.end_excl
            } else {
                other.end_excl
            };

            Self::try_new(start, end_excl)
        }

        /// Returns the convex hull (smallest interval containing both) of two intervals.
        ///
        /// Always returns a valid `I32CO`.
        #[inline]
        pub const fn convex_hull(self, other: Self) -> Self {
            let start = if self.start <= other.start {
                self.start
            } else {
                other.start
            };

            let end_excl = if self.end_excl >= other.end_excl {
                self.end_excl
            } else {
                other.end_excl
            };

            Self { start, end_excl }
        }

        /// Returns the interval strictly between two intervals.
        ///
        /// If the intervals are contiguous or overlap, returns `None`.
        #[inline]
        pub const fn between(self, other: Self) -> Option<Self> {
            let (left, right) = if self.start <= other.start {
                (self, other)
            } else {
                (other, self)
            };

            Self::try_new(left.end_excl, right.start)
        }

        /// Returns the union of two intervals.
        ///
        /// - If intervals are contiguous or overlapping, returns `One` containing the merged interval.
        /// - Otherwise, returns `Two` containing both intervals in ascending order.
        #[inline]
        pub const fn union(self, other: Self) -> OneTwo<Self> {
            if self.is_contiguous_with(other) {
                OneTwo::One(self.convex_hull(other))
            } else if self.start <= other.start {
                OneTwo::Two(self, other)
            } else {
                OneTwo::Two(other, self)
            }
        }

        /// Returns the difference of two intervals (self - other).
        ///
        /// - If no overlap, returns `One(self)`.
        /// - If partial overlap, returns `One` or `Two` depending on remaining segments.
        /// - If fully contained, returns `Zero`.
        #[inline]
        pub const fn difference(self, other: Self) -> ZeroOneTwo<Self> {
            match self.intersection(other) {
                None => ZeroOneTwo::One(self),
                Some(inter) => {
                    let left = Self::try_new(self.start, inter.start);
                    let right = Self::try_new(inter.end_excl, self.end_excl);

                    match (left, right) {
                        (None, None) => ZeroOneTwo::Zero,
                        (Some(x), None) | (None, Some(x)) => ZeroOneTwo::One(x),
                        (Some(x), Some(y)) => ZeroOneTwo::Two(x, y),
                    }
                }
            }
        }

        /// Returns the symmetric difference of two intervals.
        ///
        /// Equivalent to `(self - other) ∪ (other - self)`.
        /// - If intervals do not overlap, returns `Two(self, other)` in order.
        /// - If intervals partially overlap, returns remaining non-overlapping segments as `One` or `Two`.
        #[inline]
        pub const fn symmetric_difference(self, other: Self) -> ZeroOneTwo<Self> {
            match self.intersection(other) {
                None => {
                    if self.start <= other.start {
                        ZeroOneTwo::Two(self, other)
                    } else {
                        ZeroOneTwo::Two(other, self)
                    }
                }
                Some(inter) => {
                    let hull = self.convex_hull(other);
                    let left = Self::try_new(hull.start, inter.start);
                    let right = Self::try_new(inter.end_excl, hull.end_excl);

                    match (left, right) {
                        (None, None) => ZeroOneTwo::Zero,
                        (Some(x), None) | (None, Some(x)) => ZeroOneTwo::One(x),
                        (Some(x), Some(y)) => ZeroOneTwo::Two(x, y),
                    }
                }
            }
        }
    }
}

// ------------------------------------------------------------
// Module: Minkowski arithmetic for I32CO
// Provides checked and saturating Minkowski operations for intervals
// ------------------------------------------------------------

pub mod minkowski {
    use super::*;

    type Min = i32;
    type Max = i32;

    #[inline]
    const fn min_max4(a: i32, b: i32, c: i32, d: i32) -> (Min, Max) {
        let (min1, max1) = if a < b { (a, b) } else { (b, a) };
        let (min2, max2) = if c < d { (c, d) } else { (d, c) };
        let min = if min1 < min2 { min1 } else { min2 };
        let max = if max1 > max2 { max1 } else { max2 };
        (min, max)
    }

    #[inline]
    const fn min_max2(a: i32, b: i32) -> (Min, Max) {
        if a < b { (a, b) } else { (b, a) }
    }

    pub mod checked {
        use super::*;

        // --------------------------------------------------------
        // Interval-to-interval
        // --------------------------------------------------------
        impl I32CO {
            #[inline]
            pub const fn checked_minkowski_add(self, other: Self) -> Option<Self> {
                let Some(start) = self.start.checked_add(other.start) else {
                    return None;
                };
                let Some(end_excl) = self.end_excl.checked_add(other.end_incl()) else {
                    return None;
                };
                Some(Self::new_unchecked(start, end_excl))
            }

            #[inline]
            pub const fn checked_minkowski_sub(self, other: Self) -> Option<Self> {
                let Some(start) = self.start.checked_sub(other.end_incl()) else {
                    return None;
                };
                let Some(end_excl) = self.end_excl.checked_sub(other.start) else {
                    return None;
                };
                Some(Self::new_unchecked(start, end_excl))
            }

            #[inline]
            pub const fn checked_minkowski_mul(self, other: Self) -> Option<Self> {
                let a = self.start;
                let b = self.end_incl();
                let c = other.start;
                let d = other.end_incl();

                let Some(p1) = a.checked_mul(c) else {
                    return None;
                };
                let Some(p2) = a.checked_mul(d) else {
                    return None;
                };
                let Some(p3) = b.checked_mul(c) else {
                    return None;
                };
                let Some(p4) = b.checked_mul(d) else {
                    return None;
                };

                let (start, end_incl) = min_max4(p1, p2, p3, p4);

                let Some(end_excl) = end_incl.checked_add(1) else {
                    return None;
                };

                Some(Self::new_unchecked(start, end_excl))
            }

            #[inline]
            pub const fn checked_minkowski_div(self, other: Self) -> Option<Self> {
                if other.start <= 0 && other.end_incl() >= 0 {
                    return None;
                }

                let a = self.start;
                let b = self.end_incl();
                let c = other.start;
                let d = other.end_incl();

                let Some(p1) = a.checked_div(c) else {
                    return None;
                };
                let Some(p2) = a.checked_div(d) else {
                    return None;
                };
                let Some(p3) = b.checked_div(c) else {
                    return None;
                };
                let Some(p4) = b.checked_div(d) else {
                    return None;
                };

                let (start, end_incl) = min_max4(p1, p2, p3, p4);

                let Some(end_excl) = end_incl.checked_add(1) else {
                    return None;
                };

                Some(Self::new_unchecked(start, end_excl))
            }
        }

        // --------------------------------------------------------
        // Scalar
        // --------------------------------------------------------
        impl I32CO {
            #[inline]
            pub const fn checked_minkowski_add_n(self, n: i32) -> Option<Self> {
                let Some(start) = self.start.checked_add(n) else {
                    return None;
                };
                let Some(end_excl) = self.end_excl.checked_add(n) else {
                    return None;
                };
                Some(Self::new_unchecked(start, end_excl))
            }

            #[inline]
            pub const fn checked_minkowski_sub_n(self, n: i32) -> Option<Self> {
                let Some(start) = self.start.checked_sub(n) else {
                    return None;
                };
                let Some(end_excl) = self.end_excl.checked_sub(n) else {
                    return None;
                };
                Some(Self::new_unchecked(start, end_excl))
            }

            #[inline]
            pub const fn checked_minkowski_mul_n(self, n: i32) -> Option<Self> {
                let Some(a) = self.start.checked_mul(n) else {
                    return None;
                };
                let Some(b) = self.end_incl().checked_mul(n) else {
                    return None;
                };

                let (start, end_incl) = min_max2(a, b);

                let Some(end_excl) = end_incl.checked_add(1) else {
                    return None;
                };
                Some(Self::new_unchecked(start, end_excl))
            }

            #[inline]
            pub const fn checked_minkowski_div_n(self, n: i32) -> Option<Self> {
                if n == 0 {
                    return None;
                }
                let Some(a) = self.start.checked_div(n) else {
                    return None;
                };
                let Some(b) = self.end_incl().checked_div(n) else {
                    return None;
                };

                let (start, end_incl) = min_max2(a, b);

                let Some(end_excl) = end_incl.checked_add(1) else {
                    return None;
                };
                Some(Self::new_unchecked(start, end_excl))
            }
        }
    }

    // ========================================================
    // SATURATING
    // ========================================================
    pub mod saturating {
        use super::*;

        impl I32CO {
            #[inline]
            pub const fn saturating_minkowski_add(self, other: Self) -> Option<Self> {
                let start = self.start.saturating_add(other.start);
                let end_excl = self.end_excl.saturating_add(other.end_incl());
                Self::try_new(start, end_excl)
            }

            #[inline]
            pub const fn saturating_minkowski_sub(self, other: Self) -> Option<Self> {
                let start = self.start.saturating_sub(other.end_incl());
                let end_excl = self.end_excl.saturating_sub(other.start);
                Self::try_new(start, end_excl)
            }

            #[inline]
            pub const fn saturating_minkowski_mul(self, other: Self) -> Option<Self> {
                let a = self.start.saturating_mul(other.start);
                let b = self.start.saturating_mul(other.end_incl());
                let c = self.end_incl().saturating_mul(other.start);
                let d = self.end_incl().saturating_mul(other.end_incl());

                let (start, end_incl) = min_max4(a, b, c, d);

                let end_excl = end_incl.saturating_add(1);
                Self::try_new(start, end_excl)
            }

            #[inline]
            pub const fn saturating_minkowski_div(self, other: Self) -> Option<Self> {
                if other.start <= 0 && other.end_incl() >= 0 {
                    return None;
                }

                let a = self.start / other.start;
                let b = self.start / other.end_incl();
                let c = self.end_incl() / other.start;
                let d = self.end_incl() / other.end_incl();

                let (start, end_incl) = min_max4(a, b, c, d);

                let end_excl = end_incl.saturating_add(1);
                Self::try_new(start, end_excl)
            }
        }

        impl I32CO {
            #[inline]
            pub const fn saturating_minkowski_add_n(self, n: i32) -> Option<Self> {
                let start = self.start.saturating_add(n);
                let end_excl = self.end_excl.saturating_add(n);
                Self::try_new(start, end_excl)
            }

            #[inline]
            pub const fn saturating_minkowski_sub_n(self, n: i32) -> Option<Self> {
                let start = self.start.saturating_sub(n);
                let end_excl = self.end_excl.saturating_sub(n);
                Self::try_new(start, end_excl)
            }

            #[inline]
            pub const fn saturating_minkowski_mul_n(self, n: i32) -> Option<Self> {
                let a = self.start.saturating_mul(n);
                let b = self.end_incl().saturating_mul(n);

                let (start, end_incl) = min_max2(a, b);

                let end_excl = end_incl.saturating_add(1);
                Self::try_new(start, end_excl)
            }

            #[inline]
            pub const fn saturating_minkowski_div_n(self, n: i32) -> Option<Self> {
                if n == 0 {
                    return None;
                }

                let a = self.start / n;
                let b = self.end_incl() / n;

                let (start, end_incl) = min_max2(a, b);

                let end_excl = end_incl.saturating_add(1);
                Self::try_new(start, end_excl)
            }
        }
    }
}
