// -----------------------------------------------------------------------------
// @generated by xtask/codegen
// DO NOT EDIT MANUALLY.
// Changes will be overwritten.
// -----------------------------------------------------------------------------

use crate::res::{OneTwo, ZeroOneTwo};

#[cfg(test)]
mod between_tests;
#[cfg(test)]
mod convex_hull_tests;
#[cfg(test)]
mod difference_tests;
#[cfg(test)]
mod intersection_tests;
#[cfg(test)]
mod symmetric_difference_tests;
#[cfg(test)]
mod union_tests;

#[derive(Copy, Clone, Debug, Eq, PartialEq, Hash)]
pub struct I8CO {
    start: i8,
    end_excl: i8,
}

// ------------------------------------------------------------
// low-level api: construction / accessors / predicates
// ------------------------------------------------------------

impl I8CO {
    #[inline]
    pub const fn try_new(start: i8, end_excl: i8) -> Option<Self> {
        if start < end_excl {
            Some(Self { start, end_excl })
        } else {
            None
        }
    }

    #[inline]
    pub const fn new_unchecked(start: i8, end_excl: i8) -> Self {
        debug_assert!(start < end_excl);
        Self { start, end_excl }
    }

    #[inline]
    pub const fn start(self) -> i8 {
        self.start
    }

    #[inline]
    pub const fn end_excl(self) -> i8 {
        self.end_excl
    }

    #[inline]
    pub const fn len(self) -> i8 {
        self.end_excl - self.start
    }

    #[inline]
    pub const fn contains(self, x: i8) -> bool {
        self.start <= x && x < self.end_excl
    }

    #[inline]
    pub const fn iter(self) -> core::ops::Range<i8> {
        self.start..self.end_excl
    }

    #[inline]
    pub const fn intersects(self, other: Self) -> bool {
        !(self.end_excl <= other.start || other.end_excl <= self.start)
    }

    #[inline]
    pub const fn is_adjacent(self, other: Self) -> bool {
        self.end_excl == other.start || other.end_excl == self.start
    }

    #[inline]
    pub const fn is_contiguous_with(self, other: Self) -> bool {
        self.intersects(other) || self.is_adjacent(other)
    }
}

// ------------------------------------------------------------
// high-level api: interval algebra
// ------------------------------------------------------------

impl I8CO {
    #[inline]
    pub const fn intersection(self, other: Self) -> Option<Self> {
        let start = if self.start >= other.start {
            self.start
        } else {
            other.start
        };

        let end_excl = if self.end_excl <= other.end_excl {
            self.end_excl
        } else {
            other.end_excl
        };

        Self::try_new(start, end_excl)
    }
}

impl I8CO {
    #[inline]
    pub const fn convex_hull(self, other: Self) -> Self {
        let start = if self.start <= other.start {
            self.start
        } else {
            other.start
        };

        let end_excl = if self.end_excl >= other.end_excl {
            self.end_excl
        } else {
            other.end_excl
        };

        Self { start, end_excl }
    }
}

impl I8CO {
    #[inline]
    pub const fn between(self, other: Self) -> Option<Self> {
        let (left, right) = if self.start <= other.start {
            (self, other)
        } else {
            (other, self)
        };

        Self::try_new(left.end_excl, right.start)
    }
}

impl I8CO {
    #[inline]
    pub const fn union(self, other: Self) -> OneTwo<Self> {
        if self.is_contiguous_with(other) {
            OneTwo::One(self.convex_hull(other))
        } else if self.start <= other.start {
            OneTwo::Two(self, other)
        } else {
            OneTwo::Two(other, self)
        }
    }
}

impl I8CO {
    #[inline]
    pub const fn difference(self, other: Self) -> ZeroOneTwo<Self> {
        match self.intersection(other) {
            None => ZeroOneTwo::One(self),
            Some(inter) => {
                let left = Self::try_new(self.start, inter.start);
                let right = Self::try_new(inter.end_excl, self.end_excl);

                match (left, right) {
                    (None, None) => ZeroOneTwo::Zero,
                    (Some(x), None) | (None, Some(x)) => ZeroOneTwo::One(x),
                    (Some(x), Some(y)) => ZeroOneTwo::Two(x, y),
                }
            }
        }
    }
}

impl I8CO {
    #[inline]
    pub const fn symmetric_difference(self, other: Self) -> ZeroOneTwo<Self> {
        match self.intersection(other) {
            None => {
                if self.start <= other.start {
                    ZeroOneTwo::Two(self, other)
                } else {
                    ZeroOneTwo::Two(other, self)
                }
            }
            Some(inter) => {
                let hull = self.convex_hull(other);
                let left = Self::try_new(hull.start, inter.start);
                let right = Self::try_new(inter.end_excl, hull.end_excl);

                match (left, right) {
                    (None, None) => ZeroOneTwo::Zero,
                    (Some(x), None) | (None, Some(x)) => ZeroOneTwo::One(x),
                    (Some(x), Some(y)) => ZeroOneTwo::Two(x, y),
                }
            }
        }
    }
}
